version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - network    
  django:
    build: ./api
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - network
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      networks:
        - network

networks:
  network:
    driver: bridge
