# Generated by Django 2.0.1 on 2021-11-09 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weatherForecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='countryCode',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='temperature',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
