# Generated by Django 2.0.1 on 2021-11-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherForecast', '0002_auto_20211109_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
