# Generated by Django 2.0.1 on 2021-11-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherForecast', '0003_auto_20211109_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='countryCode',
            new_name='country_code',
        ),
    ]
