# Generated by Django 2.0.1 on 2021-11-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherForecast', '0004_auto_20211111_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
