# Generated by Django 2.0.1 on 2021-11-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherForecast', '0005_auto_20211111_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='country_code',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='weather',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
